POST http://127.0.0.1:8062/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZXNoYSIsInJvbGVzIjoid29ya2VyIiwidXNlcklkIjoiMDMzNGY0NDctMDlkYS00YWJmLTg5NzktZTY3NTk1OGJhZDY1IiwiaWF0IjoxNjkyMjA1NzcwLCJleHAiOjE2OTMwNjk3NzB9.rCKwyQ4kdkbZsykISu_8aAxA-GNml6enNj2cxRZ3jY8

{
  "description": "Fix computer"
}

###
POST http://127.0.0.1:8062/api/tasks/complete/ac991a77-a3b3-488b-b5fc-e30a5d8a6231
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZXNoYSIsInJvbGVzIjoid29ya2VyIiwidXNlcklkIjoiYmRhYmQyOTQtNjlkYi00YmQ5LWE5MmUtM2JiM2Q5OTQ0ZDM5IiwiaWF0IjoxNjkyNDcwNjMyLCJleHAiOjE2OTMzMzQ2MzJ9.9rNH3S15ExwEx4QoP86hrKewhvEtN_Jwfk6NlrWWFEc

###
POST http://127.0.0.1:8062/api/tasks/reassign-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyMSIsInJvbGVzIjoibWFuYWdlciIsInVzZXJJZCI6IjIiLCJpYXQiOjE2OTE5MzcwMTgsImV4cCI6MTY5MTk0MDYxOH0.baDBJU-p2lTVz-nIALE1NrEZ-Jrv795RqXaPTL2llNk

###
GET http://127.0.0.1:8062/api/tasks/my-tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyMSIsInJvbGVzIjoibWFuYWdlciIsInVzZXJJZCI6IjIiLCJpYXQiOjE2OTE5MzcwMTgsImV4cCI6MTY5MTk0MDYxOH0.baDBJU-p2lTVz-nIALE1NrEZ-Jrv795RqXaPTL2llNk
