server:
  port: 8061

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    locations: classpath:db/migration
    table: flyway_schema_history
  data:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      repositories:
        bootstrap-mode: default
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: ru.toughdev.ates.authn.consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
jwt:
  token:
    secret: ates-app
    expired: 864000000