###
POST http://127.0.0.1:8061/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcHBhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJ1c2VySWQiOiJjMTQ0Y2Y1Yi0yNmY0LTQ3ZmMtODgwMy0wZTkyZGNjZmMxNTkiLCJpYXQiOjE2OTIyMDU3MjQsImV4cCI6MTY5MzA2OTcyNH0.mjh5pLoa_K3JFKh6dsxqXSSj0qChv_KoI1M4IflvJ94

{
  "login": "kesha",
  "firstName": "Инокентий",
  "lastName": "Попугов",
  "email": "kesha@ates.com",
  "password": "test",
  "role": "worker"
}

###
POST http://127.0.0.1:8061/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcHBhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJ1c2VySWQiOiJjMTQ0Y2Y1Yi0yNmY0LTQ3ZmMtODgwMy0wZTkyZGNjZmMxNTkiLCJpYXQiOjE2OTIyMDU3MjQsImV4cCI6MTY5MzA2OTcyNH0.mjh5pLoa_K3JFKh6dsxqXSSj0qChv_KoI1M4IflvJ94

{
  "login": "karlo",
  "firstName": "Карло",
  "lastName": "Попугаев",
  "email": "kaflo@ates.com",
  "password": "test",
  "role": "worker"
}

###
POST http://127.0.0.1:8061/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcHBhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJ1c2VySWQiOiJjMTQ0Y2Y1Yi0yNmY0LTQ3ZmMtODgwMy0wZTkyZGNjZmMxNTkiLCJpYXQiOjE2OTIyMDU3MjQsImV4cCI6MTY5MzA2OTcyNH0.mjh5pLoa_K3JFKh6dsxqXSSj0qChv_KoI1M4IflvJ94

{
  "login": "kiki",
  "firstName": "Кики",
  "lastName": "Попугессова",
  "email": "kiki@ates.com",
  "password": "test",
  "role": "worker"
}
