server:
  port: 8062

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    locations: classpath:db/migration
    table: flyway_schema_history
  data:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      repositories:
        bootstrap-mode: default
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: ru.toughdev.ates.tasktracker.consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      "[schema.registry.url]": http://localhost:8081
      "[specific.avro.reader]": true
      "[auto.register.schemas]": false

jwt:
  token:
    secret: ates-app
